export default {
  vi: { channelHub: {
    backToProject: 'Quay lại dự án', eyebrow: 'Xuất bản', title: 'Trung tâm kênh', description: 'Xuất video đã render bất biến lên YouTube với tiến trình bền vững, thử lại, kết nối lại và khôi phục trạng thái sau tải lên.',
    refreshWorkspace: 'Làm mới không gian', refreshing: 'Đang làm mới…', destination: 'Đích đến', youtubeConnection: 'Kết nối YouTube', loadingChannels: 'Đang tải các kênh đã kết nối…', noChannel: 'Chưa kết nối kênh', noChannelHelp: 'Ủy quyền YouTube để tạo kết nối kênh đầu tiên do máy chủ quản lý. Thông tin OAuth và refresh token không đi vào trình duyệt.', openingYoutube: 'Đang mở YouTube…', connectYoutube: 'Kết nối YouTube', reconnectYoutube: 'Kết nối lại YouTube', capabilities: 'Khả năng của kênh', upload: 'Tải lên', publicPublish: 'Xuất bản công khai', schedule: 'Lên lịch', available: 'khả dụng', unavailable: 'không khả dụng', reconnectHelp: 'Ủy quyền không còn sử dụng được. Hãy kết nối lại đúng kênh từ xa trước khi tiếp tục tải lên.', publishLimited: 'Kết nối này không đảm bảo xuất bản công khai. Các điều khiển chỉ theo khả năng máy chủ báo về.',
    newUpload: 'Tải lên mới', publishRendered: 'Xuất bản video đã render', renderedVideo: 'Video đã render', noRenders: 'Không có render thành công', selectRender: 'Chọn một render', renderHelp: 'Chỉ các MP4 render bất biến thuộc dự án này được liệt kê.', renderEmptyHelp: 'Hãy tạo một render thành công trước khi xuất bản.', videoTitle: 'Tiêu đề video', titlePlaceholder: 'Tiêu đề hiển thị trên YouTube', descriptionLabel: 'Mô tả', descriptionPlaceholder: 'Mô tả tùy chọn', creatingAttempt: 'Đang tạo lượt xuất bản…', createAttempt: 'Tạo lượt xuất bản',
    selectedAttempt: 'Lượt đã chọn', attempt: 'Lượt', artifact: 'Artifact', uploaded: 'Đã tải lên', updated: 'Cập nhật', bytes: '{count} byte', uploadProgress: 'Tiến trình tải lên', indeterminate: 'Không thể xác định tiến trình vì tổng dung lượng artifact không có trong snapshot không gian này.', autoRefresh: 'Tiến trình tải lên tự làm mới khi lượt này đang chờ hoặc đang tải lên.', needsAttention: 'Xuất bản cần chú ý: {code}', statusRetryHelp: 'Video từ xa đã tồn tại. Chỉ thử lại kiểm tra trạng thái YouTube; không khởi động lại tải lên.', retryHelp: 'Thử lại giữ nguyên lượt logic và offset tiếp tục; không tạo bản tải lên từ xa trùng lặp.', reconnectAttemptHelp: 'Kết nối lại YouTube, rồi làm mới lượt này trước khi tiếp tục.', openRemote: 'Mở video từ xa', queueingRetry: 'Đang xếp hàng thử lại…', retryUpload: 'Thử lại tải lên', checkingYoutube: 'Đang kiểm tra YouTube…', retryYoutubeStatus: 'Thử lại kiểm tra trạng thái YouTube', checkYoutubeStatus: 'Kiểm tra trạng thái YouTube', refreshSavedState: 'Làm mới trạng thái đã lưu',
    durableHistory: 'Lịch sử bền vững', publishAttempts: 'Các lượt xuất bản', loadingHistory: 'Đang tải lịch sử xuất bản…', noAttempts: 'Chưa có lượt xuất bản', noAttemptsHelp: 'Tạo một lượt ở phía trên; lượt này vẫn hiển thị sau khi làm mới hoặc khởi động lại.',
    authComplete: 'Ủy quyền YouTube đã hoàn tất. Khả năng của kênh đã được làm mới.', loadFailed: 'Không thể tải không gian Channel Hub.', oauthFailed: 'Không thể bắt đầu ủy quyền YouTube.', createFailed: 'Không thể tạo lượt xuất bản.', refreshFailed: 'Không thể làm mới lượt xuất bản đã lưu.', livePaused: 'Tạm dừng làm mới tiến trình trực tiếp. Trạng thái tải lên đã lưu gần nhất vẫn được hiển thị; dùng Làm mới trạng thái đã lưu để thử lại.', youtubeStatusUnavailable: 'Trạng thái YouTube tạm thời không khả dụng. Video từ xa được giữ nguyên; hãy thử lại kiểm tra trạng thái sau.', youtubeStatusRefreshed: 'Đã làm mới trạng thái xử lý và xuất bản YouTube.', youtubeStatusFailed: 'Không thể kiểm tra trạng thái YouTube hiện tại.', retryFailed: 'Không thể xếp hàng thử lại xuất bản.',
    states: { connected: 'đã kết nối', queued: 'đang chờ', uploading: 'đang tải lên', upload_accepted: 'đã nhận tải lên', processing: 'đang xử lý', private: 'riêng tư', scheduled: 'đã lên lịch', public: 'công khai', retryable_failure: 'lỗi có thể thử lại', reconnect_required: 'cần kết nối lại', rejected: 'bị từ chối', revoked: 'đã thu hồi' }
  }},
  en: { channelHub: {
    backToProject: 'Back to project', eyebrow: 'Publishing', title: 'Channel Hub', description: 'Publish an immutable rendered video to YouTube with durable progress, retry, reconnect and post-upload status recovery.',
    refreshWorkspace: 'Refresh workspace', refreshing: 'Refreshing…', destination: 'Destination', youtubeConnection: 'YouTube connection', loadingChannels: 'Loading connected channels…', noChannel: 'No channel connected', noChannelHelp: 'Authorize YouTube to create the first server-managed channel connection. OAuth credentials and refresh tokens never enter the browser.', openingYoutube: 'Opening YouTube…', connectYoutube: 'Connect YouTube', reconnectYoutube: 'Reconnect YouTube', capabilities: 'Channel capabilities', upload: 'Upload', publicPublish: 'Public publish', schedule: 'Schedule', available: 'available', unavailable: 'unavailable', reconnectHelp: 'Authorization is no longer usable. Reconnect the same remote channel before upload can continue.', publishLimited: 'This connection cannot promise public publication. Controls remain limited to server-reported capability.',
    newUpload: 'New upload', publishRendered: 'Publish rendered video', renderedVideo: 'Rendered video', noRenders: 'No successful renders available', selectRender: 'Select a render', renderHelp: 'Only owned immutable MP4 render artifacts for this project are listed.', renderEmptyHelp: 'Create a successful render before publishing.', videoTitle: 'Video title', titlePlaceholder: 'Title shown on YouTube', descriptionLabel: 'Description', descriptionPlaceholder: 'Optional description', creatingAttempt: 'Creating publish attempt…', createAttempt: 'Create publish attempt',
    selectedAttempt: 'Selected attempt', attempt: 'Attempt', artifact: 'Artifact', uploaded: 'Uploaded', updated: 'Updated', bytes: '{count} bytes', uploadProgress: 'Upload progress', indeterminate: 'Upload progress is indeterminate because artifact total is unavailable in this workspace snapshot.', autoRefresh: 'Upload progress refreshes automatically while this attempt is queued or uploading.', needsAttention: 'Publishing needs attention: {code}', statusRetryHelp: 'The remote video already exists. Retry only the YouTube status check; do not restart the upload.', retryHelp: 'Retry preserves this logical attempt and resumable offset; it does not create a duplicate remote upload.', reconnectAttemptHelp: 'Reconnect YouTube, then refresh this attempt before continuing.', openRemote: 'Open remote video', queueingRetry: 'Queueing retry…', retryUpload: 'Retry upload', checkingYoutube: 'Checking YouTube…', retryYoutubeStatus: 'Retry YouTube status check', checkYoutubeStatus: 'Check YouTube status', refreshSavedState: 'Refresh saved state',
    durableHistory: 'Durable history', publishAttempts: 'Publish attempts', loadingHistory: 'Loading publish history…', noAttempts: 'No publish attempts yet', noAttemptsHelp: 'Create an attempt above; it remains visible here after refresh or restart.',
    authComplete: 'YouTube authorization completed. Channel capabilities have been refreshed.', loadFailed: 'Could not load the Channel Hub workspace.', oauthFailed: 'Could not start YouTube authorization.', createFailed: 'Could not create the publish attempt.', refreshFailed: 'Could not refresh the persisted publish attempt.', livePaused: 'Live progress refresh paused. The last saved upload state is still shown; use Refresh saved state to retry.', youtubeStatusUnavailable: 'YouTube status is temporarily unavailable. The remote video is preserved; retry this status check later.', youtubeStatusRefreshed: 'YouTube processing and publication status refreshed.', youtubeStatusFailed: 'Could not check the current YouTube status.', retryFailed: 'Could not queue the publish retry.',
    states: { connected: 'connected', queued: 'queued', uploading: 'uploading', upload_accepted: 'upload accepted', processing: 'processing', private: 'private', scheduled: 'scheduled', public: 'public', retryable_failure: 'retryable failure', reconnect_required: 'reconnect required', rejected: 'rejected', revoked: 'revoked' }
  }}
} as const
